# Configuration file for ML project
project:
  name: "physics_ml_project"
  data_path: "./updated_data_set_ab2_abc_ab.xlsx"
  output_dir: "./output_directory"

cluster:
  partition: "dgx"
  nodes: 1
  gpus_per_task: 1
  cpus_per_task: 20
  memory: "128G"
  time_limit: "48:00:00"

training:
  model_type: "xgboost"  # Can be ridge, lasso, randomforest, xgboost
  n_epochs: 50
  learning_rate: 0.01
  batch_size: 32

optimization:
  optuna_trials: 50
  optuna_timeout: 3600

